### ISSUE TITLE
The new feature, access with credentils doesn't work, can you provide more info in your Wiki

### ISSUE THREAD

**Issue by eliaspizarro** [tgjones/robosharp#1]
The new feature, access with credentils doesn't work, can you provide more info in your Wiki
Tried in VB.net

`
Dim backup As New RoboCommand
...
backup.Start(domain:="", username:="admin", password:="qwerty")

`

Regards

**Comment by tgjones** [comment]
I think you've logged this in the wrong repository - did you mean https://robosharp.codeplex.com?
